POST http://127.0.0.1:10001/reqapi/richieste HTTP/1.1
Content-Type: application/json

{
    "name": "pippo", 
    "cliente_id": 1, 
    "operativo_id": 1, 
    "tratta_id": 301, 
    "accepted": false 
}
