openapi: 3.0.0
info:
  title: API Gateway
  version: 1.0.0
  description: API Gateway for managing requests

paths:
  /ping: 
    get: 
      summary: ping
      operationId: ping
      responses:
        '200':
          description: OK

  /reqapi/requests/open:
    get: 
      summary: Get all open requests
      operationId: getAllOpenRequests
      responses:
        '200':
          description: OK
      
  /reqapi/requests:
    get:
      summary: Get all requests
      operationId: getAllRequests
      responses:
        '200':
          description: OK
    post:
      summary: Create a new request
      operationId: createNewRequest
      responses:
        '201':
          description: Created
  /reqapi/requests/{requestId}:
    get:
      summary: Get a request by ID
      operationId: getRequestById
      parameters:
        - in: path
          name: requestId
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: OK
        '404':
          description: Request not found
    put:
      summary: Update a request
      operationId: updateRequestById
      parameters:
        - in: path
          name: requestId
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: OK
        '404':
          description: Request not found
    delete:
      summary: Delete a request
      operationId: deleteRequestById
      parameters:
        - in: path
          name: requestId
          schema:
            type: integer
          required: true
      responses:
        '204':
          description: No Content
  /reqapi/tratta:
    get:
      summary: Get all tratta
      operationId: getAllTratta
      responses:
        '200':
          description: OK
    post:
      summary: Create a new tratta
      operationId: addNewTratta
      responses:
        '201':
          description: Created
   
      

components:
  schemas:
    Request:
      type: object
      properties:
        id:
          type: integer
        # Add other properties for request
    Client: 
      type: object
      properties: 
        id: 
          type: integer
