openapi: 3.0.0
info:
  title: API Gateway
  version: 1.0.0
  description: API Gateway for managing richieste

paths:
  /ping: 
    get: 
      summary: ping
      operationId: ping
      responses:
        '200':
          description: OK

  /richieste/open:
    get: 
      summary: Get all open richieste
      operationId: getAllOpenRichieste
      responses:
        '200':
          description: OK
      
  /richieste:
    get:
      summary: Get all richieste
      operationId: getAllRichieste
      responses:
        '200':
          description: OK
    post:
      summary: Create a new richiesta
      operationId: createNewRichiesta
      responses:
        '201':
          description: Created
  /richieste/{richiestaId}:
    get:
      summary: Get a richiesta by ID
      operationId: getRichiestaById
      parameters:
        - in: path
          name: richiestaId
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: OK
        '404':
          description: richiesta not found
    put:
      summary: Update a richiesta
      operationId: updateRichiestaById
      parameters:
        - in: path
          name: richiestaId
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: OK
        '404':
          description: richiesta not found
    delete:
      summary: Delete a richiesta
      operationId: deleteRichiestaById
      parameters:
        - in: path
          name: richiestaId
          schema:
            type: integer
          required: true
      responses:
        '204':
          description: No Content
  /tratta:
    get:
      summary: Get all tratta
      operationId: getAllTratta
      responses:
        '200':
          description: OK
    post:
      summary: Create a new tratta
      operationId: addNewTratta
      responses:
        '201':
          description: Created
   
      

components:
  schemas:
    richiesta:
      type: object
      properties:
        id:
          type: integer
        # Add other properties for richiesta
    Client: 
      type: object
      properties: 
        id: 
          type: integer
